name: Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - {
              name: "Windows latest",
              os: windows-latest
            }

    steps:
       - uses: actions/checkout@v4

       - name: Run CMake
         run: |
           cd bracket-regex
           mkdir build
           cd build
           cmake ..
           cmake --build .
           ctest -C Debug
